version: '2'

volumes:
  app:
  craftcms-logs:
  mysql:  

services:
    web:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - craftcms-logs:/var/log
        - ./app:/usr/share/nginx
      links:
        - redis
        - mysql

      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # REDIS is linked
        REDIS_HOST: redis

        # DB is linked
        DB_DRIVER: mysql
        DB_SERVER: mysql
        DB_DATABASE: craft_iot
        DB_PASSWORD: fR33d@M!
        DB_SCHEMA: public
        DB_PORT: '3306'
        DB_USER: craft_iot_poc
        LANG: C.UTF-8

    redis:
      image: redis:4.0.10-alpine
      volumes:
        - /data:/data

    mysql:
      image: mysql:5
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: fR33d@M!
        MYSQL_USER: craft_iot_poc
        MYSQL_PASSWORD: fR33d@M!
      volumes:
        - mysql:/var/lib/mysql

