version: '2'

volumes:
  app:
  craftcms-logs:
  mysql:  

services:
    web:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - craftcms-logs:/var/log
        - ./app:/usr/share/nginx
        - /usr/share/nginx/vendor
        - ./craft-iot-poc:/user/share/craft-iot-poc
      links:
        - mysql

      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # DB is linked
        ENVIRONMENT: dev
        DB_DRIVER: mysql
        DB_SERVER: mysql
        DB_DATABASE: craft_iot
        DB_PASSWORD: fR33d@M!
        DB_SCHEMA: public
        DB_PORT: '3306'
        DB_USER: craft_iot_poc
        SECURITY_KEY: F3xWhwnQYoTbyBa_zJ_Pp1B0X8LQh1V3

    mysql:
      image: mysql:5
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: fR33d@M!
        MYSQL_USER: craft_iot_poc
        MYSQL_PASSWORD: fR33d@M!
        MYSQL_DATABASE: craft_iot
      volumes:
        - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        - mysql:/var/lib/mysql

